import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.width}>
    <div className={styles.container}>
      <Head>
        <title>Chris Millar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gameboy2.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.heading}>
          Hey, I'm Chris!
        </h1>
        


        <div className={styles.grid}>
  

          <p className={styles.para}>I'm a recent MSc software development graduate eager to kickstart his career.<br/> <br/>
           I am actively looking for a software engineering position within an ambitious product-focused company that 
            can offer development training, project based learning and career progression opportunities.</p>
            
            <a
            href="Christopher Millar CV.pdf" download
            className={`${styles.card} ${styles.orange} ${styles.cv}`}
          >
            <h2>Download CV &rarr;</h2>
            <p>Check out my CV!</p>
          </a>

          <a href="https://shorturl.at/DFO69" className={`${styles.card} ${styles.blue} ${styles.link}`}>
            <h2>LinkedIn &rarr;</h2>
            <p>Connect with me on LinkedIn.</p>
          </a>
          
          <a
            href="https://github.com/cmillar113" 
            className={`${styles.card} ${styles.green} ${styles.git}`}
          >
            <h2>Github &rarr;</h2>
            <p>Check out my github!</p>
            
          </a>
          <h2>Projects</h2>
          <a
            href="https://todo-list-cmillar113.vercel.app/"
            className={`${styles.cardProjects} ${styles.purple} `}
          >
            <h2>Todo List</h2>
            <ul>     
            <li>Maintaining and mutating UI state with react hooks</li>
              <li>Persisting data between sessions via local storage</li>
              <li>Uses NextJS, deployed to Vercel</li>
            </ul>
          </a>
          <br></br>

          <a
            href="https://gym-template-gules.vercel.app/"
            className={`${styles.cardProjects} ${styles.purple} `}
          >
            <h2>Gym Website</h2>
            <ul>
            <li>Responsive web design</li>
              <li>Project used to continuously test and improve styling skills</li>
              <li>Uses NextJS, deployed to Vercel</li>
            </ul>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
      <a
            href="mailto:c.millar.113@gmail.com"
            className={`${styles.cardFull} ${styles.yellow}`}
          >
            <h2>Contact me</h2>
            <p>I'm always keen to expand my network. Let's grab a coffee!</p>
          </a>


      {/* <Image src="/carbon.png" alt='Intro' width={600} height={200}/> */}
      </footer>
    </div>
    </div>
  )
}
export default Home
